export { Vault } from './domain/entities/Vault'
export { NoteEntry } from './domain/entities/NoteEntry'
export { WatchEvent } from './domain/entities/WatchEvent'
export type { WatchEventType } from './domain/entities/WatchEvent'
export { InvalidVaultPathError, VaultNotOpenError, NoteNotFoundError, NoteNameCollisionError, EntryNotFoundError, ImageSaveError } from './domain/errors/VaultErrors'
export type { VaultRepository } from './domain/interfaces/VaultRepository'
export type { NoteRepository, NoteContent, FolderDto } from './domain/interfaces/NoteRepository'
export type { ImageRepository } from './domain/interfaces/ImageRepository'
export type { FileWatcher } from './domain/interfaces/FileWatcher'
export { OpenVault } from './application/use-cases/OpenVault'
export { GetCurrentVault } from './application/use-cases/GetCurrentVault'
export { ListNotes } from './application/use-cases/ListNotes'
export { CreateNote } from './application/use-cases/CreateNote'
export { CreateFolder } from './application/use-cases/CreateFolder'
export { RenameEntry } from './application/use-cases/RenameEntry'
export { DeleteEntry } from './application/use-cases/DeleteEntry'
export { ReadNote } from './application/use-cases/ReadNote'
export { SaveImage } from './application/use-cases/SaveImage'
export type { VaultDto, NoteEntryDto, CreatedNoteDto, RenamedEntryDto, NoteContentDto, SavedImageDto } from './application/dto'
export { InMemoryVaultRepository } from './infrastructure/repositories/InMemoryVaultRepository'
export { FsNoteRepository } from './infrastructure/repositories/FsNoteRepository'
export { FsImageRepository } from './infrastructure/repositories/FsImageRepository'
export { ChokidarFileWatcher } from './infrastructure/repositories/ChokidarFileWatcher'
export { VaultIpcHandler } from './infrastructure/ipc-handlers/VaultIpcHandler'
