export { Vault } from './domain/entities/Vault'
export { NoteEntry } from './domain/entities/NoteEntry'
export { InvalidVaultPathError, VaultNotOpenError, NoteNotFoundError, NoteNameCollisionError } from './domain/errors/VaultErrors'
export type { VaultRepository } from './domain/interfaces/VaultRepository'
export type { NoteRepository, NoteContent } from './domain/interfaces/NoteRepository'
export { OpenVault } from './application/use-cases/OpenVault'
export { GetCurrentVault } from './application/use-cases/GetCurrentVault'
export { ListNotes } from './application/use-cases/ListNotes'
export { CreateNote } from './application/use-cases/CreateNote'
export type { VaultDto, NoteEntryDto, CreatedNoteDto, NoteContentDto } from './application/dto'
export { InMemoryVaultRepository } from './infrastructure/repositories/InMemoryVaultRepository'
export { FsNoteRepository } from './infrastructure/repositories/FsNoteRepository'
export { VaultIpcHandler } from './infrastructure/ipc-handlers/VaultIpcHandler'
