export { SearchResult } from './domain/entities/SearchResult'
export { SearchEntry } from './domain/entities/SearchEntry'
export { SearchNotes } from './application/use-cases/SearchNotes'
export type { SearchResultDto, SearchEntryDto } from './application/dto'
export { SearchIpcHandler } from './infrastructure/ipc-handlers/SearchIpcHandler'
