export { WikiLink } from './domain/entities/WikiLink'
export { Backlink } from './domain/entities/Backlink'
export { Tag } from './domain/entities/Tag'
export { NoteRef } from './domain/entities/NoteRef'
export { NoteFromLinkExistsError } from './domain/errors/KnowledgeErrors'
export { ParseWikiLinks } from './application/use-cases/ParseWikiLinks'
export { FindBacklinks } from './application/use-cases/FindBacklinks'
export { FindNotesByTag } from './application/use-cases/FindNotesByTag'
export { ResolveLink } from './application/use-cases/ResolveLink'
export { CreateNoteFromLink } from './application/use-cases/CreateNoteFromLink'
export type { BacklinkDto, NoteRefDto, ResolvedLinkDto, CreatedNoteFromLinkDto } from './application/dto'
export { KnowledgeIpcHandler } from './infrastructure/ipc-handlers/KnowledgeIpcHandler'
