export { Document } from './domain/entities/Document'
export { NoDocumentOpenError, DocumentHasNoPathError } from './domain/errors/EditorErrors'
export type { DocumentRepository } from './domain/interfaces/DocumentRepository'
export { OpenDocument } from './application/use-cases/OpenDocument'
export { SaveDocument } from './application/use-cases/SaveDocument'
export { SaveAsDocument } from './application/use-cases/SaveAsDocument'
export { NewDocument } from './application/use-cases/NewDocument'
export { MarkDirty } from './application/use-cases/MarkDirty'
export type { OpenDocumentDto, SavedDocumentDto } from './application/dto'
export { InMemoryDocumentRepository } from './infrastructure/repositories/InMemoryDocumentRepository'
export { EditorIpcHandler } from './infrastructure/ipc-handlers/EditorIpcHandler'
