export { Document } from './domain/entities/Document'
export { ButtonTemplate } from './domain/entities/ButtonTemplate'
export { NoDocumentOpenError, DocumentHasNoPathError, TabNotFoundError } from './domain/errors/EditorErrors'
export type { DocumentRepository } from './domain/interfaces/DocumentRepository'
export type { ButtonTemplateRepository } from './domain/interfaces/ButtonTemplateRepository'
export { OpenDocument } from './application/use-cases/OpenDocument'
export { SaveDocument } from './application/use-cases/SaveDocument'
export { SaveAsDocument } from './application/use-cases/SaveAsDocument'
export { NewDocument } from './application/use-cases/NewDocument'
export { MarkDirty } from './application/use-cases/MarkDirty'
export { CloseDocument } from './application/use-cases/CloseDocument'
export { SwitchDocument } from './application/use-cases/SwitchDocument'
export { GetOpenDocuments } from './application/use-cases/GetOpenDocuments'
export { UpdateDocumentPath } from './application/use-cases/UpdateDocumentPath'
export { ReorderDocuments } from './application/use-cases/ReorderDocuments'
export { GetAvailableButtonTemplates } from './application/use-cases/GetAvailableButtonTemplates'
export type { OpenDocumentDto, SavedDocumentDto, NewDocumentDto, CloseDocumentDto, TabDto, OpenTabsDto, ButtonTemplateDto } from './application/dto'
export { InMemoryDocumentRepository } from './infrastructure/repositories/InMemoryDocumentRepository'
export { StaticButtonTemplateRepository } from './infrastructure/repositories/StaticButtonTemplateRepository'
export { EditorIpcHandler } from './infrastructure/ipc-handlers/EditorIpcHandler'
