export { WorkspaceState } from './domain/entities/WorkspaceState'
export type { StateRepository } from './domain/interfaces/StateRepository'
export { GetLastVault } from './application/use-cases/GetLastVault'
export { SetLastVault } from './application/use-cases/SetLastVault'
export { GetOpenTabs } from './application/use-cases/GetOpenTabs'
export { SetOpenTabs } from './application/use-cases/SetOpenTabs'
export { GetSidebarWidth } from './application/use-cases/GetSidebarWidth'
export { SetSidebarWidth } from './application/use-cases/SetSidebarWidth'
export { GetActiveTabPath } from './application/use-cases/GetActiveTabPath'
export { SetActiveTabPath } from './application/use-cases/SetActiveTabPath'
export { GetExpandedFolders } from './application/use-cases/GetExpandedFolders'
export { SetExpandedFolders } from './application/use-cases/SetExpandedFolders'
export { GetCommandBarButtons } from './application/use-cases/GetCommandBarButtons'
export { SetCommandBarButtons } from './application/use-cases/SetCommandBarButtons'
export { GetSearchPanelState } from './application/use-cases/GetSearchPanelState'
export type { SearchPanelStateDto } from './application/use-cases/GetSearchPanelState'
export { SetSearchPanelState } from './application/use-cases/SetSearchPanelState'
export { JsonStateRepository } from './infrastructure/repositories/JsonStateRepository'
export { StateIpcHandler } from './infrastructure/ipc-handlers/StateIpcHandler'
