export { WorkspaceState } from './domain/entities/WorkspaceState'
export type { StateRepository } from './domain/interfaces/StateRepository'
export { GetLastVault } from './application/use-cases/GetLastVault'
export { SetLastVault } from './application/use-cases/SetLastVault'
export { GetOpenTabs } from './application/use-cases/GetOpenTabs'
export { SetOpenTabs } from './application/use-cases/SetOpenTabs'
export { GetSidebarWidth } from './application/use-cases/GetSidebarWidth'
export { SetSidebarWidth } from './application/use-cases/SetSidebarWidth'
export { JsonStateRepository } from './infrastructure/repositories/JsonStateRepository'
export { StateIpcHandler } from './infrastructure/ipc-handlers/StateIpcHandler'
